### ISSUE TITLE
Nutrient set to extinct

### ISSUE THREAD

**Issue by emilio-berti** [gauzens/ATNr#2]
https://github.com/gauzens/ATNr/blob/c64154eb3fb41b58d98869eb5907e9e580683b13/src/Unscaled_nuts_loops.cpp#L201

This should be fixed to avoid nutrients to be set as extinct.

**Comment by emilio-berti** [comment]
I faked the test run on the converge between the armadillo and for loop versions, or it will fail to install.

**Comment by emilio-berti** [comment]
I faked the test run on the converge between the armadillo and for loop versions, or it will fail to install:
https://github.com/gauzens/ATNr/blob/f955c92c54039b10cd7d798456b72be736596d12/tests/testthat/test-Schneider.R#L59-L60

**Comment by gauzens** [comment]
fixed
